### ISSUE TITLE
Mask not working correctly; works fine in spine-ts player

### ISSUE THREAD

**Issue by randrade23** [pixijs/spine#428]
Hi,

I have a Spine animation that renders correctly in the Spine editor and in the spine-ts player, but when using pixi-spine there is a mask that does not apply correctly - it does not clip some deformed bones.

Expected result:

![image](https://user-images.githubusercontent.com/2223723/147558733-7dce4ba1-c635-4530-ac25-36b701e41dba.png)

Actual result:

![image](https://user-images.githubusercontent.com/2223723/147561753-3520abe9-6cca-46c9-8211-89655c1b4591.png)

I can send the Spine animation via email so that the issue can be checked, let me know who I can send it to please.

Thank you!

**Comment by ivanpopelyshev** [comment]
Hi! Please re-post it at https://github.com/pixijs/pixijs/discussions , because currently i dont know who's responsible for the plugin.

Update your pixijs6, i think it was fixed already.

**Comment by randrade23** [comment]
Hi Ivan, thank you! I already tried updating to the latest versions of pixi-spine and Pixi v6 but the issue persists. I'll open another issue on the Pixi repo.

**Comment by randrade23** [comment]
Just leaving a running example here if anyone has any ideas on this repo: [Demo](https://d5lfyopf9muc4.cloudfront.net/spine-demo/index.html)

**Comment by ivanpopelyshev** [comment]
That's where you can debug this thing and get "geometry.graphicsData[0].something` , bounds, stuff:

![image](https://user-images.githubusercontent.com/695831/147567729-3c5cc772-7cd7-477a-a0e0-c3f6d318d096.png)

Its a stencil mask. For more info, please post in pixijs main discussions.
